server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/producer_service_db?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true