server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/producer_service_db?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#          format_sql: true

  kafka:
    bootstrap-servers:
      - localhost:19093
      - localhost:19094
      - localhost:19095
    producer:
      #      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: activityDto:com.parakramaba.producerservice.dto.UserActivityDto
