version: "3"

services:
  zookeeper1:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper1
    ports:
      - 12181:12181
    volumes:
      - "zookeeper1_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      #      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_PORT_NUMBER: 12181

  zookeeper2:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper2
    ports:
      - 12182:12182
    volumes:
      - "zookeeper2_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOO_PORT_NUMBER: 12182

  kafka1:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka1
    ports:
      - 19093:19093
    volumes:
      - "kafka1_data:/bitnami"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:12181,zookeeper2:12182
      KAFKA_CFG_LISTENERS: CLIENT://:9093,EXTERNAL://:19093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka1:9093,EXTERNAL://localhost:19093
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper1
      - zookeeper2

  kafka2:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka2
    ports:
      - 19094:19094
    volumes:
      - "kafka2_data:/bitnami"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:12181,zookeeper2:12182
      KAFKA_CFG_LISTENERS: CLIENT://:9094,EXTERNAL://:19094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka2:9094,EXTERNAL://localhost:19094
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper1
      - zookeeper2

  kafka3:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka3
    ports:
      - 19095:19095
    volumes:
      - "kafka3_data:/bitnami"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:12181,zookeeper2:12182
      KAFKA_CFG_LISTENERS: CLIENT://:9095,EXTERNAL://:19095
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka3:9095,EXTERNAL://localhost:19095
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper1
      - zookeeper2

  control_center1:
    image: confluentinc/cp-enterprise-control-center:7.1.6-1-ubi8
    container_name: control_center1
    depends_on:
      - kafka1
      - kafka2
      - kafka3

    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka1:9093,kafka2:9094,kafka3:9095"
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
    volumes:
      - "control_center_data:/bitnami"

volumes:
  zookeeper1_data:
    driver: local
  zookeeper2_data:
    driver: local
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local
  control_center_data:
    driver: local
  db-leach: {}